name: demo30
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.4
  url_launcher: ^5.7.6
  fluttertoast: ^3.1.0
#  roundcheckbox: ^1.0.0
#  mysql1: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
  - assets/tabs/home-1.png
  - assets/tabs/home-2.png
  - assets/tabs/me-1.png
  - assets/tabs/me-2.png
  - assets/tabs/product-1.png
  - assets/tabs/product-2.png
  - assets/tabs/tourist-1.png
  - assets/tabs/tourist-2.png
  - assets/banner/banner1.png
  - assets/banner/banner2.png
  - assets/banner/banner3.png
  - assets/banner/banner4.png
  - assets/banner/banner5.png
  - assets/icons/arrowDownBrown.png
  - assets/icons/arrowDownGrey.png
  - assets/coursesPic/cbt.png
  - assets/coursesPic/ptgz.png
  - assets/coursesPic/pyzg.png
  - assets/coursesPic/zdx.png
  - assets/vrPic/zs.png
  - assets/vrPic/lz.png
  - assets/vrPic/slhz.png
  - assets/vrPic/dhgc.png
  - assets/vrPic/js.png
  - assets/vrPic/sc.png
  - assets/vr360Pic/zs360.png
  - assets/vr360Pic/lz360.png
  - assets/vr360Pic/slhz360.png
  - assets/vr360Pic/dhgc360.png
  - assets/vr360Pic/js360.png
  - assets/vr360Pic/sc360.png
  - assets/indexPic/index.png
  - assets/indexPic/login.png
  - assets/about/logo.png
  - assets/goodsImg/fan1.png
  - assets/goodsImg/fan2.png
  - assets/goodsImg/fan3.png
  - assets/goodsImg/fan4.png
  - assets/goodsImg/paperCut.png
  - assets/goodsImg/ship.png
  - assets/icons/bin.png
  - assets/icons/add.png
  - assets/icons/sub.png
  - assets/icons/address.png
  - assets/icons/rewrite.png
  - assets/goodsInfo/fan2.png
  - assets/goodsInfo/fan1.jpg
  - assets/goodsInfo/fan3.jpg
  - assets/goodsInfo/fan4.jpg
  - assets/goodsInfo/papercut.jpg
  - assets/goodsInfo/ship.jpg
  - assets/icons/kefu.png
  - assets/icons/niming.png
  - assets/icons/cha.png
  - assets/icons/shopcart.png